name: flutter_group_sliver
description: A new Flutter package project.
version: 0.0.3

environment:
  sdk: ">=2.18.0 <4.0.0"
  # flutter: "3.10.5"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter